# Generated by Django 4.2.7 on 2023-11-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff_panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='OfferTable',
        ),
    ]
