# Generated by Django 4.2.7 on 2023-11-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff_panel', '0002_rename_user_offertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('givenotification', models.CharField(max_length=100)),
            ],
        ),
    ]
