# Generated by Django 4.2.7 on 2023-11-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff_panel', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pointaddmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('pointno', models.CharField(max_length=10)),
            ],
        ),
    ]
