# Generated by Django 4.2.7 on 2023-11-25 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.CharField(default='A1', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(default='S1', max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(default='0000', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdminLoggedIn',
            fields=[
                ('logged_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='admin_panel.admin')),
                ('logged_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
