# Generated by Django 4.2.7 on 2023-11-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('bus_number', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('d1', models.CharField(max_length=50)),
                ('d2', models.CharField(max_length=50)),
                ('d3', models.CharField(max_length=50)),
                ('d4', models.CharField(max_length=50)),
                ('d5', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('bus_numbber', models.IntegerField()),
                ('seat_number', models.CharField(max_length=5)),
                ('user_id', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
