# Generated by Django 4.2.7 on 2023-11-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0002_alter_tickets_ticket_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='bus_numbber',
            new_name='bus_number',
        ),
    ]
