# Generated by Django 4.2.7 on 2023-11-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0003_rename_bus_numbber_tickets_bus_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='buses',
            name='bus_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
